from typing import Protocol, Dict, Any, Optional

class AudioProtocol(Protocol):
    def hablar(self, texto: str) -> None: ...
    def escuchar(self, timeout_silencio: Optional[float] = None, limite_segundo: Optional[int] = None) -> str: ...
    @property
    def ultima_interaccion(self) -> float: ...
    @ultima_interaccion.setter
    def ultima_interaccion(self, value: float) -> None: ...

class AIProtocol(Protocol):
    def route_command(self, text: str) -> Dict[str, Any]: ...
    def summarize(self, text: str) -> str: ...
    def summarize_session(self, messages: list) -> Optional[str]: ...

class MemoryProtocol(Protocol):
    def guardar(self, rol: str, texto: str) -> None: ...
    def cargar(self) -> list: ...

class ActionProtocol(Protocol):
    def set_obsidian_mcp(self, mcp: Any) -> None: ...
    def set_ai_service(self, ai_svc: Any) -> None: ...
    def execute(self, config: Dict[str, Any]) -> str: ...

class TelemetryProtocol(Protocol):
    def send(self, state: str, prompt: str = "", response: str = "") -> None: ...
    def close(self) -> None: ...
